### ISSUE TITLE
`PreferencesViewController.swift` Missing in Master.

### ISSUE THREAD

**Issue by thePsguy** [jariz/Noti#50]
The PreferencesViewController Scene in storyboard has its Class set to `PreferencesViewController`
But the class `PreferencesViewController` has not been defined in any file. Maybe `PreferencesViewController.swift` was not added to git?

Once this class is available, I'm certain I'd be able to fix issue #47 as well.

@jariz, you must have this file locally available right?

**Comment by ABeltramo** [comment]
Seems like the project gone cold after v0.2. We can't even build our updated version based on pull request because we are missing a lot from the release (like the new icon?)!
I really like this piece of code but it's sad that is left alone in the dark.. 😢
@jariz *where are you*? 🆘

**Comment by jariz** [comment]
Hey guys, yes, master is kind of messed up because of a failed merge. I apologise. I figured #40 was going to be merged soon so I didn't bother with it all that much, but, #40 still requires quite a bit of work first to be merged with master.
So yes, going to fix master (lots of missing icons and stuff too, I believe), and will hopefully merge your PR tonight @ABeltramo, sorry guys, been really busy with personal stuff.

**Comment by thePsguy** [comment]
Should this be closed? This issue has been resolved I suppose?
