### ISSUE TITLE
can't see incoming calls

### ISSUE THREAD

**Issue by taliaku** [jariz/Noti#57]
Is this feature works?
Do I have to change something in the pushbullet settings to make it work?
Thanks

**Comment by ABeltramo** [comment]
It's working for me on v0.2. Other notifications are working? Have you set end-to-end encryption?

**Comment by ABeltramo** [comment]
Having the same issue. The problem seems to be related to one particular setting inside the Pushbullet App on mobile (not related to Noti). Following [this reddit post](https://www.reddit.com/r/PushBullet/comments/7ue3sz/pushbullet_considers_incoming_call_notifications/) if "Skip silent notifications" is enabled Pushbullet no longer send the notification of an incoming call. Disabling it seems to solve the issue.  
Attaching a screenshot of the notification settings on Android.
![1502725203-picsay](https://user-images.githubusercontent.com/1122217/36602847-59663b8a-18b9-11e8-89e9-bd37b41a6010.png)
